### ISSUE TITLE
not really a issue your awesome

### ISSUE THREAD

**Issue by goblinsrus4** [moraell/KinectMocap4Blender#11]
I have been testing this out and I got to say its the best and easiest so far, 
I was wondering though is there a way we could use more than 1 Kinect v2 for more precise  captures

**Comment by moraell** [comment]
Well... thank you !
Currently, you cannot use 2 sensors with this add-on. It would require a lot of work, if it is even possible with the official SDK. Another issue : I cannot afford a second sensor. I'm investigating other ways to improve precision, however.
