### ISSUE TITLE
New to Git/GitHub

### ISSUE THREAD

**Issue by hunnerman** [moraell/KinectMocap4Blender#13]
Hi there,

I'm very interested in using your plug-in for school research. However, I don't have any experience with git or github. I downloaded your files and installed the python plug-in in Blender, however it isn't working as shown in the video.

What steps am I missing?

Thanks.

**Comment by moraell** [comment]
Hi,
I need more information to help you. I assume you have copied both kynect_mocap.py and kinectMocap4Blender.pyd in Blender's addons directory ? Do you have an error message in the system console (open it with "Window/Toggle system console") ? If you don't, then it should be working. You need an armature (even a single bone is enough but you can make a full skeleton or activate the "rigify" add-on and add a meta-rig), select it in object mode, then switch to pose mode. The kinectMocap4Blender should appear (press 'N' to open the panels in Blender 2.80 ot 'T' for the tools panel in Blender 2.79). When you have the panel, just click on "Initialize tracking system" and you should now have the exact layout shown in the video.

**Comment by hunnerman** [comment]
Hi,
I don't see any file in what I downloaded called kinectMocap4Blender.pyd. I have installed the kinect_mocap.py however, I can't find the previously mentioned file.

**Comment by hunnerman** [comment]
I am getting an error. Here it is.
<img width="959" alt="Annotation 2019-10-23 210618" src="https://user-images.githubusercontent.com/56854757/67447292-014c5980-f5d9-11e9-9b67-836861f6913d.png">

**Comment by moraell** [comment]
I think you have not downloaded the release archive. In the download page (https://github.com/moraell/KinectMocap4Blender/releases), download the file named KinectMocap4Blender_V1.4.zip.

**Comment by hunnerman** [comment]
Thank you for your help! I didn't realize that there was a separate place to download from. I look forward to using your plugin!
