### ISSUE TITLE
Compatible with Rigify?

### ISSUE THREAD

**Issue by hunnerman** [moraell/KinectMocap4Blender#14]
Hi there,

Its me again. I was wondering if you had ever attempted to use your plugin after having altered positions of bones in the meta-rig and then generating a complete rig with the Rigify add-on? I assumed that the bones that it generates would act the same as the standard meta-rig, however all that happens when I begin tracking and move around is a slight wiggle/swivel of the hips.

If you don't have any suggestions, that's okay, I just thought I'd ask.

Thanks!

**Comment by moraell** [comment]
Hi,
I don't understand what you mean by "after having altered positions of bones in the meta-rig and then generating a complete rig with the Rigify add-on".
I use mainly rigify armatures and modify them to suit my 3D models, and it works fine. Be careful, however ! If you have more than one armature in a project, don't forget to select the one you want to do the capture for at the top of the add-on configuration panel.
