### ISSUE TITLE
No support for kinect for windows

### ISSUE THREAD

**Issue by Hunanbean** [moraell/KinectMocap4Blender#17]
Even though i own the Kinect for windows, which i purchased because it has the license for this type of use with it, i cannot use it because it is not V2? there is no technical reason this should not work. i am very disappointed that the original kinect for windows was intentionally left out. i understand leaving the 360 version out, but i purchased the kinect for windows specifically to get the usage license, which is seemingly neglected by this project.

**Comment by moraell** [comment]
Hi, the reason kinect V1 for windows is not supported is the same as kinect 360 : compatibility with windows 10. Kinect V2 for windows, however, uses the same SDK so it should work with this project (as far as I know).

**Comment by moraell** [comment]
Not an issue

**Comment by Hunanbean** [comment]
You are the second person to mention compatibility with windows 10 issues, but i have none with any other apps that i use my kinect v1 with. 1.8 SDK
