### ISSUE TITLE
Nowhere in menu

### ISSUE THREAD

**Issue by boberski666** [moraell/KinectMocap4Blender#20]
I installed and activated plugin:
![image](https://user-images.githubusercontent.com/2800036/83558346-3166be00-a513-11ea-84ff-dc5a40ea8d59.png)
Bit I cannot find it on toolbar:
![image](https://user-images.githubusercontent.com/2800036/83558404-4a6f6f00-a513-11ea-93b1-8bda4c4eb2fb.png)

Any idea whats wrong?

**Comment by moraell** [comment]
Are you in pose mode? If you are, then maybe you have an error message in the console that would help me  identify the issue.
I see you have NI mate. If you installed it for Kinect, it also installed its own drivers which may conflict with the official Kinect drivers.

**Comment by boberski666** [comment]
Ok I have it, it is howing only in pose mode. Question: I need to ser every bone to mate this work or only one to se if it is tracking?

**Comment by moraell** [comment]
Just one is enough to test the system.
