### ISSUE TITLE
missing kinectMocap4Blender.py

### ISSUE THREAD

**Issue by trashmaster9000** [moraell/KinectMocap4Blender#21]
if i install the addon and want to enable it it just says it cant find "kinectMocap4Blender.py" in the scripts/addons folder...

where can i find this file?

**Comment by moraell** [comment]
It's in the downloadable release zip.

**Comment by trashmaster9000** [comment]
oof, sorry, i've downloaded the files via the "clone" button...

found it, thanks.

and thank you for your awesome work!
