### ISSUE TITLE
Where's Kinect tab in Blender 2.90?

### ISSUE THREAD

**Issue by Kieaer** [moraell/KinectMocap4Blender#25]
No errors in console.
Where's Kinect tab?

**Comment by topot** [comment]
> No errors in console.
> Where's Kinect tab?

![sdfgsfegesg](https://user-images.githubusercontent.com/8147916/117014209-8adefa80-ad2b-11eb-9ba4-2bb835300e1e.jpg)

You can found it in the pose mode of amarture. but.. I guess you can't use it. bcoz... it is not completed work. 

all bone is working on the world space. The rotation of bone is not correct work.
