### ISSUE TITLE
Xbox 360 Kinect Sensor

### ISSUE THREAD

**Issue by JoelJ99** [moraell/KinectMocap4Blender#5]
Hello, I have the same problem that JustinA762 is having. Is there a way for your code to work for the 360 kinect and how did you record it to blender?

**Comment by moraell** [comment]
Hello, sorry I answer so late. You just can't use kinect 360 easily with windows 10, and the SDK is different anyway. For older versions of windows, I guess you can adapt the code to the 360 Kinect SDK.
As for your second question : the c++ part is just a small library that allows the pyhton script (in Blender) to get the Kinect data through Boost library. This is then processed in Blender to recursively get the angle of each bone and record it in the current frame. It is as simple as that.
