### ISSUE TITLE
pyd file expensive to compile

### ISSUE THREAD

**Issue by thelabcat** [moraell/KinectMocap4Blender#7]
Can you compile the PYD file and include it? Best I can tell from the SDK licenses you can.

I installed Visual Studio, downloaded boost and engie (err... whatever), and then ran into another dependency. That, combined with little C++ knowledge, stopped the compile.

**Comment by moraell** [comment]
It is already inlcuded in the release zip file : https://github.com/moraell/KinectMocap4Blender/releases/download/V1.2/KinectMocap4Blender_V1.2.zip

**Comment by thelabcat** [comment]
I couldn't find it before. Will try download again...

PS: PTL and thx for the addon!

**Comment by thelabcat** [comment]
After: Praise the Lord it's in there! Thank you.
