### ISSUE TITLE
Great update, but crash on start.

### ISSUE THREAD

**Issue by thelabcat** [moraell/KinectMocap4Blender#9]
![Screenshot](https://user-images.githubusercontent.com/53358500/63708805-69620780-c803-11e9-9db7-57b666c6d9f0.png)
Upon clicking start, this error showed.

**Comment by moraell** [comment]
Hi! It seems that you only updated the python file. You also need to update the compiled C++ library (.pyd file).  You can find matching files for each version in the zip release file, under 2.80 or 2.79 directory.

**Comment by thelabcat** [comment]
I'm sure I did. That does seem to be what happened, though. Will retry extraction. Can you retest from the upload? Meanwhile, here's a backpedaled version for other readers.
[Kinect_Blender_1.3.5.zip](https://github.com/moraell/KinectMocap4Blender/files/3552448/Kinect_Blender_1.3.5.zip)

Or I think on git: https://github.com/zargulthewizard/KinectMocap4Blender-V1.3.5.git

**Comment by moraell** [comment]
I checked the released package as soon as I read your first message, I am a trained professional. To be sure, I just checked again. The release package is correct. The problem is on your side. The signature of the init() method has changed from v1.3 to v1.4. The only way to have your error message is to use a v1.4 python script with an older version of the pyd library. (If you compile it yourself, please check that you pulled the last commit)

**Comment by thelabcat** [comment]
Okay, thanks. Will retry. Just to make sure, am re-downloading the 1.4 commit.

BTW, unrelated, but do you know how to read the depth sensor data directly? I'm wondering if I could use a color ramp to automatically replace far away backgrounds with transparency (basically would require video-ing from the color camera and depth camera at the same time to different files) I would put this somewhere else but I am new to GitHub so I'm not sure how.

**Comment by thelabcat** [comment]
Well, now I really don't know where I'm wrong. As a last ditch attempt, this is the archive I'm downloading: https://github.com/moraell/KinectMocap4Blender/releases/download/1.4/KinectMocap4Blender_V1.4.zip, and I'm using the 2.80 version (in 2.80 release). If you can't replicate the bug with that, I guess it's my system or something I'm not mentioning (happens to plumbers and Doc Martin all the time).

**Comment by thelabcat** [comment]
Just wanted to say that this turned out to be my fault, because I was using blender's automatic installer and UnInstaller at one point, ￼ which did not know to remove the old PYD file. Yes, the new PYD file was in blender's system add-ons folder,￼￼￼￼ but the old one was still in AppData and it reverted to that.
